#!/usr/bin/env python3
"""User-facing launcher. Reads harness/run/settings.yaml (the single control
surface), generates one ale_claw preset per requested arm + one experiment yaml
into the stack, and prints (or runs with --launch) the exact launch command.

Arms map (skills, prep):
  base=(off,off)  skills=(on,off)  prep=(off,on)  skills_prep=(on,on)

The prep on/off is carried per-agent (config.domain_prep) so all arms live in ONE
run with ONE output root. Prep hyperparameters travel as env vars set by the
printed command; domain_prep.py reads them (defaults preserved if unset).

Stdlib only (no PyYAML) — runs with any python3. See harness/run/README.md.

Usage on the run box, from the stack dir:
  python3 harness/run/launch.py --stack . --per-arm            # print the command
  python3 harness/run/launch.py --stack . --per-arm --launch   # generate + run
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import presets as brc  # noqa: E402  (stdlib-only helper library; see presets.py)

# arm_id -> (with_skills, domain_prep)
ARMS = {
    "base":        (False, False),
    "skills":      (True,  False),
    "prep":        (False, True),
    "skills_prep": (True,  True),
}

EXP_NAME = "harness_compare"


def _scalar(v: str):
    v = v.strip()
    if v.startswith("[") and v.endswith("]"):
        return [x.strip() for x in v[1:-1].split(",") if x.strip()]
    low = v.lower()
    if low in ("true", "false"):
        return low == "true"
    try:
        return int(v)
    except ValueError:
        return v.strip("\"'")


def load_settings(path: Path) -> dict:
    """Minimal stdlib parser for our own settings.yaml (flat keys + one nested
    level + inline lists). Avoids a PyYAML dependency so the launcher runs with
    any python, like presets.py."""
    root: dict = {}
    cur = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        if not line[:1].isspace():
            key, _, val = line.partition(":")
            key = key.strip()
            if val.strip() == "":
                cur = root[key] = {}
            else:
                root[key] = _scalar(val)
                cur = None
        elif cur is not None:
            key, _, val = line.strip().partition(":")
            cur[key.strip()] = _scalar(val)
    return root


def experiment_yaml(name, agent_ids, suffix, tasks, out_root, concurrency, wall_time_s,
                    cleanup_mode="delete") -> str:
    # cleanup_mode=delete removes each unit's container when it ends. Outputs are
    # pulled to .logs before cleanup, so nothing is lost. "keep" accumulates one
    # live sandbox per unit and will starve the box on a large run.
    y = (
        "# GENERATED by harness/run/launch.py — do not hand-edit.\n"
        f"name: {name}\nsecret_file: secret/.env\n\nagents:\n"
        + "".join(f"  - configs/agents/{a}.yaml\n" for a in agent_ids)
        + "environment: configs/environments/docker_nogcs_keep.yaml\n"
        f"tasks: {tasks}\n\noutput:\n  root: {out_root}\n"
        f"concurrency: {concurrency}\nwall_time_s: {wall_time_s}\n"
        f"cleanup_mode: {cleanup_mode}\n"
    )
    if suffix:
        y += "prompt_suffix: " + brc.yaml_block_scalar(suffix, 2) + "\n"
    return y


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stack", required=True, help="ale_run stack dir")
    ap.add_argument("--settings", default=str(HERE / "settings.yaml"))
    ap.add_argument("--launch", action="store_true", help="also run the command (nohup)")
    ap.add_argument("--per-arm", action="store_true",
                    help="one run per arm, each at run.concurrency, all launched together "
                         "(arms progress simultaneously; total = arms x concurrency)")
    args = ap.parse_args()

    stack = Path(args.stack).resolve()
    if not (stack / "ale_run").is_dir():
        print(f"error: {stack} is not an ale_run stack", file=sys.stderr)
        return 2

    st = load_settings(Path(args.settings))
    arms = st.get("arms") or list(ARMS)
    all_skills = brc.load_skills()
    which = (st.get("skills") or {}).get("which") or list(all_skills)
    skills = {k: all_skills[k] for k in which if k in all_skills}
    prep = st.get("prep") or {}
    run = st.get("run") or {}
    tasks = run.get("tasks", "selected_tasks/research_batch_26.txt")
    concurrency = int(run.get("concurrency", 8))
    out_root = run.get("output_root", ".logs/ale/harness_compare")
    wall = int(run.get("wall_time_s", 86400))
    cleanup = run.get("cleanup_mode", "delete")
    api_eps = run.get("api_endpoints") or []
    agent = st.get("agent") or {}
    model = agent.get("model", "openai/gpt-5.6-sol")
    max_turns = int(agent.get("max_turns", 100000))
    thinking = agent.get("thinking_level", "medium")

    agent_ids = []
    for arm in arms:
        if arm not in ARMS:
            print(f"warn: unknown arm {arm!r} (skip); valid: {list(ARMS)}", file=sys.stderr)
            continue
        with_skills, domain_prep = ARMS[arm]
        aid = f"ale_claw_{arm}"
        y = brc.ale_claw_agent_yaml(skills, with_skills=with_skills,
                                    agent_id=aid, domain_prep=domain_prep,
                                    model=model, max_turns=max_turns,
                                    thinking_level=thinking)
        (stack / f"configs/agents/{aid}.yaml").write_text(y, encoding="utf-8")
        agent_ids.append(aid)
    if not agent_ids:
        print("error: no valid arms", file=sys.stderr)
        return 2

    env_lines = [
        f'export ALE_DOMAIN_PREP_SEARCH={"1" if prep.get("search") else "0"}',
        f'export ALE_DOMAIN_PREP_MAX_TOKENS={int(prep.get("max_tokens", 3000))}',
        f'export ALE_DOMAIN_PREP_MAX_NOTES_CHARS={int(prep.get("max_notes_chars", 12000))}',
        f'export ALE_DOMAIN_PREP_MAX_DIGEST_CHARS={int(prep.get("digest_chars", 4000))}',
    ]
    env_block = (
        "unset http_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY ALL_PROXY\n"
        "set -a; . secret/.env; set +a\n"
        "export PATH=$HOME/.local/bin:$PATH\n"
        + "\n".join(env_lines) + "\n"
    )

    if args.per_arm:
        # One experiment per arm, each at `concurrency`, all launched together so
        # the arms advance simultaneously. All nest under out_root -> summarize
        # reads the shared root and groups by arm id.
        runs = []
        for aid in agent_ids:
            nm = f"{EXP_NAME}_{aid.replace('ale_claw_', '')}"
            (stack / f"exp_{nm}.yaml").write_text(
                experiment_yaml(nm, [aid], brc.INVARIANT, tasks, out_root, concurrency, wall, cleanup),
                encoding="utf-8")
            runs.append(nm)
        # Rotate (key, base) endpoint prefixes across arms so no single endpoint
        # is a bottleneck. secret/.env is already sourced, so the vars expand.
        launch = env_block + "".join(
            ((api_eps[i % len(api_eps)] + " ") if api_eps else "")
            + f"nohup .venv/bin/python -m ale_run run exp_{nm}.yaml > {nm}.log 2>&1 & disown\n"
            for i, nm in enumerate(runs))
        target = out_root
        mode = f"per-arm ({len(runs)} runs x concurrency {concurrency} = {len(runs) * concurrency} total)"
    else:
        (stack / f"exp_{EXP_NAME}.yaml").write_text(
            experiment_yaml(EXP_NAME, agent_ids, brc.INVARIANT, tasks, out_root, concurrency, wall, cleanup),
            encoding="utf-8")
        launch = env_block + (
            f"nohup .venv/bin/python -m ale_run run exp_{EXP_NAME}.yaml > {EXP_NAME}.log 2>&1 & disown\n")
        target = f"{out_root}/{EXP_NAME}"
        mode = f"combined (1 run x concurrency {concurrency})"

    print(f"# agent:  model={model} max_turns={max_turns} thinking={thinking}")
    print(f"# arms:   {agent_ids}")
    print(f"# mode:   {mode}   cleanup_mode={cleanup}")
    print(f"# api:    {len(api_eps) or 1} endpoint(s) rotated across arms")
    print(f"# skills: {list(skills)}   prep: search={bool(prep.get('search'))} "
          f"max_tokens={prep.get('max_tokens', 3000)} notes_chars={prep.get('max_notes_chars', 12000)}")
    print("# ---- launch command (run from the stack dir) ----")
    print(launch)
    print("# ---- inspect results ----")
    print(f"python3 harness/run/summarize.py {target} --baseline ale_claw_base")

    if args.launch:
        print("# ---- launching ----", flush=True)
        subprocess.run(["bash", "-lc", launch], cwd=str(stack), check=False)
        print("launched (nohup).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
