#!/usr/bin/env python3
"""Preset/config building blocks. HELPER LIBRARY — not an entry point.

The single entry point is `launch.py`, which reads `settings.yaml` and calls into
here. There is deliberately no `main()`: an earlier version of this file also
generated its own competing preset scheme (ale_claw_skills/noskills + pi_*) that
wrote the SAME filenames launch.py uses, so whichever ran last silently won. That
duplicate generator is gone; edit settings.yaml and run launch.py.

Contents:
  INVARIANT           the constant anti-cheat prompt suffix (run/invariant.txt)
  load_skills()       harness/skills/*/SKILL.md -> {name: text}
  yaml_block_scalar() text -> a YAML block scalar
  ale_claw_agent_yaml() one ale_claw arm preset
"""
from __future__ import annotations

from pathlib import Path

HARNESS = Path(__file__).resolve().parent.parent          # .../harness
SKILLS_DIR = HARNESS / "skills"
INVARIANT = (HARNESS / "run" / "invariant.txt").read_text(encoding="utf-8").strip()


def load_skills() -> dict[str, str]:
    """Read every harness/skills/<name>/SKILL.md verbatim."""
    out: dict[str, str] = {}
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        out[skill_md.parent.name] = skill_md.read_text(encoding="utf-8")
    return out


def yaml_block_scalar(text: str, indent: int) -> str:
    pad = " " * indent
    lines = text.rstrip("\n").split("\n")
    return "|\n" + "\n".join((pad + ln) if ln.strip() else "" for ln in lines)


def ale_claw_agent_yaml(
    skills: dict[str, str],
    *,
    with_skills: bool,
    agent_id: str,
    task_specific_prep: bool = False,
    prep_max_steps: int = 30,
    prep_timeout_s: int = 1800,
    verifier: bool = False,
    verifier_max_steps: int = 30,
    verifier_max_review_rounds: int = 1,
    verifier_writer_checks: int = 2,
    prep_self_check: bool = True,
    writer_self_review_hint: bool = False,
    model: str = "openai/gpt-5.6-sol",
    max_turns: int = 100000,
    thinking_level: str = "medium",
) -> str:
    """One ale_claw arm preset.

    Every experimental switch is written explicitly so presets cannot inherit a
    changed default. Runtime hyperparameters come from settings.yaml.
    """
    head = (
        "# GENERATED by harness/run/launch.py from settings.yaml — do not hand-edit.\n"
        f"harness: ale_claw\nid: {agent_id}\nexecutor: local\nmodel: {model}\n\nconfig:\n"
        f"  max_turns: {max_turns}\n  thinking_level: \"{thinking_level}\"\n"
        "  flush_thinking_level: \"off\"\n  compaction_thinking_level: \"off\"\n"
        "  vision_thinking_level: \"off\"\n  gui_thinking_level: \"off\"\n"
        "  substrate_transport: mcp\n  gui_transport: null\n"
        "  disable_delegate_gui: true\n"
        "  disabled_tools:\n    - web_search\n    - computer\n    - analyze_image\n"
    )
    head += (
        f"  task_specific_prep: {'true' if task_specific_prep else 'false'}\n"
        f"  task_specific_prep_max_steps: {prep_max_steps}\n"
        f"  task_specific_prep_timeout_s: {prep_timeout_s}\n"
        f"  verifier: {'true' if verifier else 'false'}\n"
        f"  verifier_max_steps: {verifier_max_steps}\n"
        f"  verifier_max_review_rounds: {verifier_max_review_rounds}\n"
        f"  verifier_writer_checks: {verifier_writer_checks}\n"
        f"  task_specific_prep_self_check: {'true' if prep_self_check else 'false'}\n"
        f"  writer_self_review_hint: {'true' if writer_self_review_hint else 'false'}\n"
    )
    if with_skills:
        head += "  skill_sources:\n"
        for name, text in skills.items():
            head += f"    {name}: {yaml_block_scalar(text, 6)}\n"
    return head
