#!/usr/bin/env python3
"""Preset/config building blocks. HELPER LIBRARY — not an entry point.

The single entry point is `launch.py`, which reads `settings.yaml` and calls into
here. There is deliberately no `main()`: an earlier version of this file also
generated its own competing preset scheme (ale_claw_skills/noskills + pi_*) that
wrote the SAME filenames launch.py uses, so whichever ran last silently won. That
duplicate generator is gone; edit settings.yaml and run launch.py.

Contents:
  INVARIANT           the constant anti-cheat prompt suffix (run/invariant.txt)
  load_skills()       harness/skills/*/SKILL.md -> {name: text}
  yaml_block_scalar() text -> a YAML block scalar
  ale_claw_agent_yaml() one ale_claw arm preset (skills on/off, prep on/off)
"""
from __future__ import annotations

from pathlib import Path

HARNESS = Path(__file__).resolve().parent.parent          # .../harness
SKILLS_DIR = HARNESS / "skills"
INVARIANT = (HARNESS / "run" / "invariant.txt").read_text(encoding="utf-8").strip()


def load_skills() -> dict[str, str]:
    """Read every harness/skills/<name>/SKILL.md verbatim."""
    out: dict[str, str] = {}
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        out[skill_md.parent.name] = skill_md.read_text(encoding="utf-8")
    return out


def yaml_block_scalar(text: str, indent: int) -> str:
    pad = " " * indent
    lines = text.rstrip("\n").split("\n")
    return "|\n" + "\n".join((pad + ln) if ln.strip() else "" for ln in lines)


def ale_claw_agent_yaml(skills: dict[str, str], *, with_skills: bool, agent_id: str,
                        domain_prep: bool = False, model: str = "openai/gpt-5.6-sol",
                        max_turns: int = 100000, thinking_level: str = "medium") -> str:
    """One ale_claw arm preset.

    `id` disambiguates arms so their output dirs never collide. `domain_prep`
    toggles capability B per-agent so one experiment can hold prep-on and prep-off
    arms. model / max_turns / thinking_level come from settings.yaml (`agent:`),
    so every hyperparameter lives in one file. max_turns defaults to 100000, i.e.
    effectively uncapped: COGNITION forbids turn/time caps because an unequal
    budget silently manufactures fake effects. The API endpoint comes from the
    environment (see harness/run/README.md).
    """
    head = (
        "# GENERATED by harness/run/launch.py from settings.yaml — do not hand-edit.\n"
        f"harness: ale_claw\nid: {agent_id}\nexecutor: local\nmodel: {model}\n\nconfig:\n"
        f"  max_turns: {max_turns}\n  thinking_level: \"{thinking_level}\"\n"
        "  flush_thinking_level: \"off\"\n  compaction_thinking_level: \"off\"\n"
        "  vision_thinking_level: \"off\"\n  gui_thinking_level: \"off\"\n"
        "  substrate_transport: mcp\n  gui_transport: null\n"
        "  disable_delegate_gui: true\n"
        "  disabled_tools:\n    - web_search\n    - computer\n    - analyze_image\n"
    )
    if domain_prep:
        head += "  domain_prep: true\n"
    if with_skills:
        head += "  skill_sources:\n"
        for name, text in skills.items():
            head += f"    {name}: {yaml_block_scalar(text, 6)}\n"
    return head
